<?php

namespace AppBundle\Repository;

/**
 * acercaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class acercaRepository extends \Doctrine\ORM\EntityRepository
{
}
