<?php

namespace AppBundle\Repository;

/**
 * categoria_notiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoria_notiRepository extends \Doctrine\ORM\EntityRepository
{
}
