<?php

namespace AppBundle\Repository;

/**
 * galeriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class galeriaRepository extends \Doctrine\ORM\EntityRepository
{
}
