<?php

namespace AppBundle\Repository;

/**
 * programasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class programasRepository extends \Doctrine\ORM\EntityRepository
{
}
