<?php

namespace AppBundle\Repository;

/**
 * ProyectosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectosRepository extends \Doctrine\ORM\EntityRepository
{
}
