app_default:
    resource: "@AppBundle/Resources/config/routing/default.yml"
    prefix: /

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /user

app_noticia:
    resource: "@AppBundle/Resources/config/routing/noticia.yml"
    prefix: /

app_actividades:
    resource: "@AppBundle/Resources/config/routing/actividades.yml"
    prefix: /
    
app_proyectos:
    resource: "@AppBundle/Resources/config/routing/proyectos.yml"
    prefix: /
    



